config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms, only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :blog_articles
  resources :articles
  get 'about', to: 'static#about'
  root 'static#index'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/blog_article.rb
class BlogArticle < ApplicationRecord

  mount_uploader :image, ImageBlogUploader
  
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord

  
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blog_articles_controller.rb
class BlogArticlesController < ApplicationController

before_action :set_blog_article, only: [ :show, :edit, :update, :destroy]

def index
  @articles = BlogArticle.all
end

def show

end

def new
  @article = BlogArticle.new
end

def create
  @article = BlogArticle.new(blog_article_params)
    unless @article.save
      render :new
    else
      redirect_to @article
    end
end

def edit
  
end

def update
   if @article.update_attributes(blog_article_params)
      redirect_to @article
    else
      render :edit
    end
end

def destroy
  @article.destroy
  redirect_to blog_articles_path
end

private

  def set_blog_article
    @article = BlogArticle.find(params[:id])  
  end

  def blog_article_params
    params.require(:blog_article).permit(:title, :sub_title, :content, :author, :image)
  end

end

app/controllers/contact_forms_controller.rb
class ContactFormsController < InheritedResources::Base

  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      render :submit
      ContactFormMailer.contact_form_recieved(@contact_form).deliver
    else
      render :new
    end
  end

  private

    def contact_form_params
      params.require(:contact_form).permit(:full_name, :email, :message)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

def index
  
end

def show
  
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_article_helper.rb
module BlogArticleHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/blog_articles/_blog_article.html.erb
<style type="text/css">
    article{
        background-color: #E0E0E0;
        padding: 10px;
        margin-bottom: 10px;
        margin-top: 10px;
    }
    figure img{
        width: 100%;
        height: 100%;
    }
    .glyphicon-folder-open,
    .glyphicon-user,
    .glyphicon-calendar,
    .glyphicon-eye-open,
    .glyphicon-comment{
        padding: 5px;
</style>

<div class="container">
  <div class="row">
    <div class="col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">
        <article>
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <figure>
                        <img src="<%= blog_article.image.url(:blogThumb) %>" style="width:280px;height:160px;"">
                    </figure>
                </div>
                <div class="col-sm-6 col-md-8">
                    <span class="label label-default pull-right"><i class="glyphicon glyphicon-comment"></i>50</span>
                    <h4><%= blog_article.title %></h4>
                    <p><%= strip_tags(blog_article.content.first(100))+"... " %></p>
                    <section>
                        <i class="glyphicon glyphicon-folder-open"></i>Bootstrap
                        <i class="glyphicon glyphicon-user"> <%= blog_article.author %></i>
                        <i class="glyphicon glyphicon-calendar">
                            <%= blog_article.created_at.to_date %></i>
                            <%= link_to 'More details', blog_article_path(blog_article), class: 'btn btn-default btn-sm pull-right' %>
                        </section>
                    </div>
                </div>
            </article>

        </div>
    </div>
</div>

app/views/blog_articles/_form.html.erb
  <div class="container">
  <%= form_for @article, html: { multipart: true } do |f| %>
    
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :sub_title %>
      <%= f.text_field :sub_title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :content %>
      <%= f.trix_editor :content, class: 'editor' %>
    </div>

    <div class="form-group">
      <%= f.label :author %>
      <%= f.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.file_field :image %>
    </div>

    <div class="form-group">
    <%= f.submit "Submit" %>
    </div>

  <% end %>
  </div>

app/views/blog_articles/edit.html.erb
<%= render 'form' %>

app/views/blog_articles/index.html.erb
<%= render @articles %>

app/views/blog_articles/new.html.erb
<%= render 'form' %>

app/views/blog_articles/show.html.erb
<style>@import url('https://fonts.googleapis.com/css?family=Open+Sans');
  body{font-family: 'Open Sans', sans-serif;}
  .header{position:relative;overflow:hidden;max-height:350px;display:flex;align-items:center;justify-content:center}
  .text{
    /*-webkit-column-count: 2; 
    -moz-column-count: 2; 
    column-count: 2; */  
    margin-top:15px;        
  }
  .statistics > p{margin-bottom:2px;}
  .statistics > p > span.label{background-color:white;color:gray;}
  .side{background:#fafafa;padding-top:15px}
  .side > img { margin-bottom:15px;}
  .semi-title{font-weight: bold;margin-top:30px;}
  .title{    
    position: absolute;
    bottom: 45px;
    padding: 7px;
    right: 25px;
    padding-left: 25px;
    padding-right: 30px;
    color: white;
    background: rgba(0,0,0,0.5);
  }
  .sub-title{    
    position: absolute;
    bottom: 94px;
    padding: 7px;
    right: 25px;
    padding-left: 12px;
    padding-right: 12px;
    color: orange;
    background: rgba(0,0,0,0.7);
  }        
  .name-author{
    position: absolute;
    bottom: 35px;
    left: 100px;
    font-size: 11px;
    color: white;
    background: black;
    padding: 2px;
    padding-right: 10px;
    padding-left: 22px;
    margin-left: -21px;
    z-index: 1;
    font-weight: 500;            
  }
  .photo-author{
    max-height: 70px;
    padding: 2px;
    position: absolute;
    left: 25px;
    bottom: 25px;
    background: white;
    z-index: 3;            
  }
  .triangulo{
    position:absolute;
    bottom:0px;
    left:0px;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 60px 0 0 1200px;
    border-color: transparent transparent transparent #ffffff;
  }
  .row-eq-height {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
  }   

  @media (max-width: 426px) {
    .header{
      margin-left: -15px;
      margin-top: -15px;
      margin-right: -15px;
    }
    .title{
      font-size:15px;
      bottom:-12px;
      right:0px;
      padding-left:10px;
      padding-right:10px;
    }
    .photo-author{
      max-height:45px;
      left:5px;
      bottom:40px;
    }
    .name-author{
      font-size:9px;
      margin-left:-63px;
      bottom:44px;
    }
    .sub-title{
      right:0px;
      bottom:18px;
      padding:5px;
      font-size:10px;
    }
  }
</style>

<div class="container">
  <div class="header">
    <img style="width:100%" src="<%= @article.image.url(:blogBackground) %>">
    <div class="triangulo"></div>
    <div class="profile">
      <img class="photo-author img-circle" src="http://www.asoeasy.com/resources/head/user_head.png">
      <span class="name-author"><%= @article.author %></span>
    </div>
    <h5 class="sub-title"><%= @article.sub_title %></h5>
    <h2 class="title"><%= @article.title %></h2>
  </div>

  <div class="row">   
    <div class="col-md-10"> 

      <div class="article">
        <h2><%= @article.title %></h2>
        <text><%= @article.content.html_safe %></text>

        <div class="container">
          <br>
          <ul class="list-unstyled list-inline">
            <li><i class="fa fa-calendar"></i><%= @article.created_at.to_date %></li>
            <li><i class="fa fa-user"></i><%= @article.author %></li>
            <li><i class="fa fa-comments"></i> <a href="#">24 Comments</a></li>
          </ul>

          <ul class="list-unstyled list-inline blog-tags">
            <li>
              <a href="#"><span class="fa fa-tag"></span> Example tags</a>
            </li>
            <li>
              <a href="#"><span class="fa fa-tag"></span> Example tags</a>
            </li>
            <li>
              <a href="#"><span class="fa fa-tag"></span> Example tags</a>
            </li>
          </ul>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/contact_forms/_form.html.erb
<div class="container ">
  <div class="row well">
    <h1 class="text-center">Contact Us</h1><br>

    <%= form_for contact_form, :method => :post do |f| %>
    <% if contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>
      <ul>
        <% contact_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :full_name %>
        <%= f.text_field :full_name, required: true, class: 'form-control', placeholder: 'How can we call you'%>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, required: true, class: 'form-control', placeholder: 'example@mail.com'%>
      </div>
    </div>

    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, required: true, class: 'form-control', placeholder: 'Your message', rows: "7"%>
      </div>

      <div class="actions">
        <%= f.submit "Send Message", class: 'btn btn-success btn-lg btn-block'%>
        <br>
      </div>
    </div>
    <% end %>
    


    <br><hr><br>
    <div class="container">
      <div class="row-fluid">
        <div class="col-md-8">
          <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2621.8101633129895!2d24.709012566804745!3d48.91900898226628!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4730c16ae2f37afb%3A0x2a00a9870320ef62!2z0LLRg9C70LjRhtGPINCh0ZbRh9C-0LLQuNGFINGB0YLRgNGW0LvRjNGG0ZbQsiwgMjMsINCG0LLQsNC90L4t0KTRgNCw0L3QutGW0LLRgdGM0LosINCG0LLQsNC90L4t0KTRgNCw0L3QutGW0LLRgdGM0LrQsCDQvtCx0LvQsNGB0YLRjA!5e0!3m2!1suk!2sua!4v1489920806532"></iframe>
        </div>

        <div class="col-md-4">
          <h2>Snail mail</h2>
          <address>
            <strong>Extim City business center</strong><br>
            Sichovych Strilciv, 23 street<br>
            Ukraine<br>
            Ivano-Frankivsk<br>
            <abbr title="Phone number">Phone:</abbr> +38 (011) 44 55 777
          </address>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/contact_forms/edit.html.erb
<h1>Editing Contact Form</h1>

<%= render 'form', contact_form: @contact_form %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Forms</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_forms.each do |contact_form| %>
      <tr>
        <td><%= contact_form.full_name %></td>
        <td><%= contact_form.email %></td>
        <td><%= contact_form.message %></td>
        <td><%= link_to 'Show', contact_form %></td>
        <td><%= link_to 'Edit', edit_contact_form_path(contact_form) %></td>
        <td><%= link_to 'Destroy', contact_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Form', new_contact_form_path %>

app/views/contact_forms/new.html.erb
<!-- <h1>New Contact Form</h1> -->

<%= render 'form', contact_form: @contact_form %>

<%#= link_to 'Back', contact_forms_path %>

app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @contact_form.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_form.message %>
</p>

<%= link_to 'Edit', edit_contact_form_path(@contact_form) %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/submit.html.erb
<div class="container ">
  
  <div class="row well">
    <h1 class="text-center">Contact Us</h1><br>

    <h2 class="text-center">Thank you for your message</h2>

    <%#= link_to 'New message', new_contact_form_path %>
    <br><hr><br>
    <div class="container">
      <div class="row-fluid">
        <div class="col-md-8">
          <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2621.8101633129895!2d24.709012566804745!3d48.91900898226628!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4730c16ae2f37afb%3A0x2a00a9870320ef62!2z0LLRg9C70LjRhtGPINCh0ZbRh9C-0LLQuNGFINGB0YLRgNGW0LvRjNGG0ZbQsiwgMjMsINCG0LLQsNC90L4t0KTRgNCw0L3QutGW0LLRgdGM0LosINCG0LLQsNC90L4t0KTRgNCw0L3QutGW0LLRgdGM0LrQsCDQvtCx0LvQsNGB0YLRjA!5e0!3m2!1suk!2sua!4v1489920806532"></iframe>
        </div>

        <div class="col-md-4">
          <h2>Snail mail</h2>
          <address>
            <strong>Extim City business center</strong><br>
            Sichovych Strilciv, 23 street<br>
            Ukraine<br>
            Ivano-Frankivsk<br>
            <abbr title="Phone number">Phone:</abbr> +38 (011) 44 55 777
          </address>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">


<!--footer-->
<footer class="footer1">
  <div class="container">

    <div class="row"><!-- row -->
      
      <div class="col-lg-3 col-md-3"><!-- widgets column left -->

        <ul class="list-unstyled clear-margins"><!-- widgets -->
          <li class="widget-container widget_nav_menu"><!-- widgets list -->
            <h1 class="title-widget">Company</h1>
            <ul>
              <li><a  href="<%= about_path%>"><i class="fa fa-angle-double-right"></i> About Us</a></li>
              <li><a  href="<%= new_contact_form_path%>"><i class="fa fa-angle-double-right"></i> Contact Us</a></li>
              <li><a  href="<%= blog_articles_path %>"><i class="fa fa-angle-double-right"></i> Our Blog</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
            </ul>
          </li>
        </ul>
        
      </div><!-- widgets column left end -->
      
      
      
      <div class="col-lg-3 col-md-3"><!-- widgets column left -->
        
        <ul class="list-unstyled clear-margins"><!-- widgets -->
          <li class="widget-container widget_nav_menu"><!-- widgets list -->
            <h1 class="title-widget">Academy</h1>
            <ul>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
            </ul>
          </li>
        </ul>
        
        
      </div><!-- widgets column left end -->
      
      
      
      <div class="col-lg-3 col-md-3"><!-- widgets column left -->
        
        <ul class="list-unstyled clear-margins"><!-- widgets -->
          <li class="widget-container widget_nav_menu"><!-- widgets list -->
            <h1 class="title-widget">Career</h1>
            <ul>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
              <li><a  href="#somecontent"><i class="fa fa-angle-double-right"></i> Some Content</a></li>
            </ul>
          </li>
        </ul>
        
      </div><!-- widgets column left end -->
      
      
      <div class="col-lg-3 col-md-3"><!-- widgets column center -->
        
        <ul class="list-unstyled clear-margins"><!-- widgets -->
          <li class="widget-container widget_recent_news"><!-- widgets list -->
            
            <h1 class="title-widget">Contact Detail </h1>
            <div class="footerp"> 
              <h2 class="title-median">Soft corp.</h2>
              <p><b>Email id:</b> <a href="mailto:info@webenlance.com">info@webenlance.com</a></p>
              <p><b>Helpline Numbers </b>
                <b style="color:#ffc106;">(8AM to 10PM):</b>  +91-8130890090, +91-8130190010  </p>                
                <p><b>Corp Office / Postal Address</b></p>
                <p><b>Phone Numbers : </b>7042827160, </p>
                <p> 034-27571832, 3498712304</p>
              </div>
              
              <div class="social-icons">
                <ul class="nomargin">
                  <a href="https://www.facebook.com/bootsnipp"><i class="fa fa-facebook-square fa-3x social-fb" id="social"></i></a>
                  <a href="https://twitter.com/bootsnipp"><i class="fa fa-twitter-square fa-3x social-tw" id="social"></i></a>
                  <a href="https://plus.google.com/+Bootsnipp-page"><i class="fa fa-google-plus-square fa-3x social-gp" id="social"></i></a>
                  <a href="mailto:bootsnipp@gmail.com"><i class="fa fa-envelope-square fa-3x social-em" id="social"></i></a>
                </ul>
              </div>

            </li>
          </ul>
          
        </div>
      </div>
    </div>
  </footer>
  <!--header-->

  <div class="footer-bottom">

    <div class="container">

      <div class="row">

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

          <div class="copyright">

            © 2017 YK  All rights fucked

          </div>

        </div>

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

          <div class="design">

          <a target="_blank" href="https://ancient-plateau-89465.herokuapp.com/">BusinessWebPage by YK</a>

         </div>

       </div>

     </div>

   </div>

 </div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><img alt="Brand" height="23" width="23" src="http://dl.frugal-labs.com/img/web.png"></a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="<%= root_path %>"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
          Some Feathure<span class="caret"></span></a>
          <ul class="dropdown-menu"> 
            <li><a href="#">Action</a></li> 
            <li><a href="#">Another action</a></li> 
            <li><a href="#">Something else here</a></li> <li role="separator" class="divider"></li> 
            <li><a href="#">Separated link</a></li> 
            <li role="separator" class="divider"></li> 
            <li><a href="#">One more separated link</a></li> 
          </ul>
        </li>
        <li>
        <a href="<%= blog_articles_path %>"><span class="glyphicon glyphicon-list-alt"></span> Blog</a></li>
        <li><a href="<%= about_path%>"><span class="glyphicon glyphicon-info-sign"></span> About</a></li>
        <li><a href="<%= new_contact_form_path%>"><span class="glyphicon glyphicon-envelope"></span> Contact</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BusinessWebPage</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  
  <%= render "layouts/header" %>
  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <ul>
    <% #if user_signed_in? %>
    <li>
      <%#= link_to "#{current_user.email}", edit_user_registration_path, class: 'nav-link' %> 
    </li>   
  
    <li>
      <%#= link_to "Sign out", destroy_user_session_path, method: :delete, class: 'nav-link' %> 
    </li>        
  
    <%# else %>
  
    <li>
      <%#= link_to "Sign in", new_user_session_path, class: 'nav-link' %> 
    </li>
  
    <% #end %>
  </ul> -->
  <br><br>
  <%= yield %>

  <%= render "layouts/footer" %>

</body>
</html>

app/views/main/_carousel.html.erb
<!-- Wrapper for slides -->
<div class="carousel-inner banner" role="listbox">
  <% Article.last(4).each do |a| %>
    <% if a == Article.last %>
      <div class="item active">
    <% else %>
      <div class="item">
    <% end %>
      <div class="col-sm-6 col-sm-offset-1 slide">
        <h1><%= a.title %></h1>
        <h2><%= a.body %></h2>
        
        <%= link_to 'READ MORE', article_path(a), class: 'bunner btn btn-primary' %>
        <div class="clearfix"></div>
      </div>
    </div>
  <% end -%>
</div>

 <div class="control-box">
    <a data-slide="prev" href="#myCarousel" class="carousel-control left"><span class="fa fa-angle-double-left"></span></a>
    <a data-slide="next" href="#myCarousel" class="carousel-control right">  <span class="fa fa-angle-double-right"></span></a>
  </div>
  <!-- /.control-box -->   

app/views/main/_carousel1.html.erb
  <div id="myCarousel1" class="carousel slide" data-ride="carousel">
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <% BlogArticle.last(4).each do |a| %>
        <% if a == BlogArticle.last %>
          <div class="item active">
        <% else %>
          <div class="item">
        <% end %>
          <div class="col-sm-12">
              
              <h2><b><%= a.title %></b></h2>

              <img src="<%= a.image.url(:blogMain) %>"  class="img-responsive">

              <h2><span class="fa fa-calendar"></span><%= " "+a.created_at.to_date.to_s+" " %><!--<span class="fa fa-comment"></span> No Comment --></h2>
              <p><%= strip_tags(a.content.first(425))+"... " %>   
              <%= link_to 'READ MORE', blog_article_path(a)%>
              </p>

          </div>
        </div>
      <% end %>
    </div>

    <div class="control-box1">                            
      <a data-slide="prev" href="#myCarousel1" class="carousel-control left"><span class="fa fa-angle-double-left"></span></a>
      <a data-slide="next" href="#myCarousel1" class="carousel-control right"><span class="fa fa-angle-double-right"></span></a>
    </div>
  <!-- /.control-box -->   

  </div>

app/views/main/_testemonial.html.erb
<div id="myCarousel2" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel2" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel2" data-slide-to="1"></li>
      <li data-target="#myCarousel2" data-slide-to="2"></li>
      <li data-target="#myCarousel2" data-slide-to="3"></li>
    </ol>

    <% Testimonial.last(4).each do |t| %>
      <% if t == Testimonial.last %>
        <div class="item active">
      <% else %>
        <div class="item">
      <% end %>

        <div class="col-sm-12">
          <div class="circle col-sm-2">
            <img src="http://www.revlocal.com/Files/images/Portraits/jfalvo_200_(2).jpg" "<%#= t.avatar.url(:thumb) %>" class="img-circle img-responsive">
          </div>
          <h2><%= t.author %></h2>
          <p><%= t.body %> <br/> <small><b><%= t.company %></b></small></p>
        </div>
      </div>
      <% end %>

    </div>
  </div>